version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: DOCKERFILE.db
    image: docker.io/znmeb/odot_crash_data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5439:5432
    env_file: ./bin/.env
  api:
    build:
      context: .
      dockerfile: DOCKERFILE.api
    image: bhgrant/hackoregon_geodjango
    command: ./bin/local-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./bin/.env
